[env:testing_device]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    knolleary/PubSubClient @ ^2.8

build_flags = 
    -DFIRMWARE_VERSION='"v1.0.1"'
    -DBUILD_DATE='"2026-06-22"'
